//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspenlaub.Net.GitHub.CSharp.Oust.Model.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspenlaub.Net.GitHub.CSharp.Oust.Model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check {0}.
        /// </summary>
        internal static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the one and only check box.
        /// </summary>
        internal static string CheckSingle {
            get {
                return ResourceManager.GetString("CheckSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear {0}.
        /// </summary>
        internal static string ClearInputText {
            get {
                return ResourceManager.GetString("ClearInputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of script.
        /// </summary>
        internal static string EndOfScript {
            get {
                return ResourceManager.GetString("EndOfScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End script if contents &apos;{0}&apos; is recognized.
        /// </summary>
        internal static string EndScriptIfRecognizeIdOrClassContents {
            get {
                return ResourceManager.GetString("EndScriptIfRecognizeIdOrClassContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End script if contents &apos;{1}&apos; is recognized in {0}.
        /// </summary>
        internal static string EndScriptIfRecognizeWithContents {
            get {
                return ResourceManager.GetString("EndScriptIfRecognizeWithContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input &apos;{0}&apos; into the one and only field.
        /// </summary>
        internal static string InputIntoSingleText {
            get {
                return ResourceManager.GetString("InputIntoSingleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input &apos;{0}&apos; into {1}.
        /// </summary>
        internal static string InputText {
            get {
                return ResourceManager.GetString("InputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find &apos;{0}&apos;.
        /// </summary>
        internal static string NotExpectedContents {
            get {
                return ResourceManager.GetString("NotExpectedContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find &apos;{0}&apos; in {1}.
        /// </summary>
        internal static string NotExpectedContentsInControl {
            get {
                return ResourceManager.GetString("NotExpectedContentsInControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without first {0} element.
        /// </summary>
        internal static string NotExpectedFirstIdOrClass {
            get {
                return ResourceManager.GetString("NotExpectedFirstIdOrClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without {0}th {1} element.
        /// </summary>
        internal static string NotExpectedNthIdOrClass {
            get {
                return ResourceManager.GetString("NotExpectedNthIdOrClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without second {0} element.
        /// </summary>
        internal static string NotExpectedSecondIdOrClass {
            get {
                return ResourceManager.GetString("NotExpectedSecondIdOrClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not selected in {1}.
        /// </summary>
        internal static string NotExpectedSelection {
            get {
                return ResourceManager.GetString("NotExpectedSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without third {0} element.
        /// </summary>
        internal static string NotExpectedThirdIdOrClass {
            get {
                return ResourceManager.GetString("NotExpectedThirdIdOrClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press {0}.
        /// </summary>
        internal static string Press {
            get {
                return ResourceManager.GetString("Press", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the one and only button.
        /// </summary>
        internal static string PressSingle {
            get {
                return ResourceManager.GetString("PressSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognize {0}.
        /// </summary>
        internal static string Recognize {
            get {
                return ResourceManager.GetString("Recognize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognize contents &apos;{0}&apos;.
        /// </summary>
        internal static string RecognizeIdOrClassContents {
            get {
                return ResourceManager.GetString("RecognizeIdOrClassContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognize OK.
        /// </summary>
        internal static string RecognizeOkay {
            get {
                return ResourceManager.GetString("RecognizeOkay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognize &apos;{1}&apos; selected in {0}.
        /// </summary>
        internal static string RecognizeSelected {
            get {
                return ResourceManager.GetString("RecognizeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognize {0} with contents &apos;{1}&apos;.
        /// </summary>
        internal static string RecognizeWithContents {
            get {
                return ResourceManager.GetString("RecognizeWithContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &apos;{0}&apos; in {1}.
        /// </summary>
        internal static string SelectOption {
            get {
                return ResourceManager.GetString("SelectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step type cannot be displayed.
        /// </summary>
        internal static string StepTypeCannotBeDisplayed {
            get {
                return ResourceManager.GetString("StepTypeCannotBeDisplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Script &apos;{0}&apos;.
        /// </summary>
        internal static string SubScript {
            get {
                return ResourceManager.GetString("SubScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncheck {0}.
        /// </summary>
        internal static string Uncheck {
            get {
                return ResourceManager.GetString("Uncheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncheck the one and only check box.
        /// </summary>
        internal static string UncheckSingle {
            get {
                return ResourceManager.GetString("UncheckSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait a minute.
        /// </summary>
        internal static string WaitAMinute {
            get {
                return ResourceManager.GetString("WaitAMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait ten seconds.
        /// </summary>
        internal static string WaitTenSeconds {
            get {
                return ResourceManager.GetString("WaitTenSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With first {0}.
        /// </summary>
        internal static string WithFirst {
            get {
                return ResourceManager.GetString("WithFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With first {0} element.
        /// </summary>
        internal static string WithFirstElement {
            get {
                return ResourceManager.GetString("WithFirstElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With {0}th {1}.
        /// </summary>
        internal static string WithNth {
            get {
                return ResourceManager.GetString("WithNth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With {0}th {1} element.
        /// </summary>
        internal static string WithNthElement {
            get {
                return ResourceManager.GetString("WithNthElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With second {0}.
        /// </summary>
        internal static string WithSecond {
            get {
                return ResourceManager.GetString("WithSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With second {0} element.
        /// </summary>
        internal static string WithSecondElement {
            get {
                return ResourceManager.GetString("WithSecondElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With third {0}.
        /// </summary>
        internal static string WithThird {
            get {
                return ResourceManager.GetString("WithThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With third {0} element.
        /// </summary>
        internal static string WithThirdElement {
            get {
                return ResourceManager.GetString("WithThirdElement", resourceCulture);
            }
        }
    }
}
