//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspenlaub.Net.GitHub.CSharp.Oust.Application.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspenlaub.Net.GitHub.CSharp.Oust.Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced to next step.
        /// </summary>
        internal static string AdvancedToNextStep {
            get {
                return ResourceManager.GetString("AdvancedToNextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advancing to next step.
        /// </summary>
        internal static string AdvancingToNextStep {
            get {
                return ResourceManager.GetString("AdvancingToNextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling script &quot;{0}&quot; not found.
        /// </summary>
        internal static string CallingScriptNotFound {
            get {
                return ResourceManager.GetString("CallingScriptNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling script step not found in calling script &quot;{0}&quot;.
        /// </summary>
        internal static string CallingScriptStepNotFound {
            get {
                return ResourceManager.GetString("CallingScriptStepNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check box not found or not unique in instance {0} of {1}.
        /// </summary>
        internal static string CheckBoxNotFoundOrNotUnique {
            get {
                return ResourceManager.GetString("CheckBoxNotFoundOrNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consolidate Scripts And Sub Scripts.
        /// </summary>
        internal static string ConsolidateProgressCaption {
            get {
                return ResourceManager.GetString("ConsolidateProgressCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control {0} not found in instance {1} of {2}.
        /// </summary>
        internal static string ControlNotFound {
            get {
                return ResourceManager.GetString("ControlNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        internal static string ControlTitle {
            get {
                return ResourceManager.GetString("ControlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine if there is a form context or not.
        /// </summary>
        internal static string CouldNotDetermineFormContext {
            get {
                return ResourceManager.GetString("CouldNotDetermineFormContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine if instance {0} of {1} is there or not.
        /// </summary>
        internal static string CouldNotDetermineIfInstanceXOfYIsThereOrNot {
            get {
                return ResourceManager.GetString("CouldNotDetermineIfInstanceXOfYIsThereOrNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not extract sub script.
        /// </summary>
        internal static string CouldNotExtractSubScript {
            get {
                return ResourceManager.GetString("CouldNotExtractSubScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not input into {0} in instance {1} of {2}.
        /// </summary>
        internal static string CouldNotInput {
            get {
                return ResourceManager.GetString("CouldNotInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not input into instance {0} of {1}.
        /// </summary>
        internal static string CouldNotInputIntoInstanceXOfY {
            get {
                return ResourceManager.GetString("CouldNotInputIntoInstanceXOfY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not navigate to &quot;{0}&quot;.
        /// </summary>
        internal static string CouldNotNavigateToUrl {
            get {
                return ResourceManager.GetString("CouldNotNavigateToUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could press the Select File button.
        /// </summary>
        internal static string CouldNotPressSelectFileButton {
            get {
                return ResourceManager.GetString("CouldNotPressSelectFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not verify if whe document contains deprecated bootstrap class/-es.
        /// </summary>
        internal static string CouldNotVerifyIfDocumentContainsDeprecatedBootstrapClasses {
            get {
                return ResourceManager.GetString("CouldNotVerifyIfDocumentContainsDeprecatedBootstrapClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document contains deprecated bootstrap class/-es: {0}.
        /// </summary>
        internal static string DocumentContainsDeprecatedBootstrapClasses {
            get {
                return ResourceManager.GetString("DocumentContainsDeprecatedBootstrapClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element was not found or is not an anchor.
        /// </summary>
        internal static string ElementNotFoundOrNotAnAnchor {
            get {
                return ResourceManager.GetString("ElementNotFoundOrNotAnAnchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element is not a div, an anchor or an input element.
        /// </summary>
        internal static string ElementWithIdOrClassNotFound {
            get {
                return ResourceManager.GetString("ElementWithIdOrClassNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step over failed, script step to be executed again.
        /// </summary>
        internal static string ErrorSteppingOver {
            get {
                return ResourceManager.GetString("ErrorSteppingOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control {0} in instance {1} of {2} does not have the expected contents &apos;{3}&apos;.
        /// </summary>
        internal static string ExpectedContentsNotFound {
            get {
                return ResourceManager.GetString("ExpectedContentsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control {0} in instance {1} of {2} does not have the expected contents &apos;{3}&apos;. Actual contents is &apos;{4}&apos;.
        /// </summary>
        internal static string ExpectedContentsNotFoundInstead {
            get {
                return ResourceManager.GetString("ExpectedContentsNotFoundInstead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exp. contents.
        /// </summary>
        internal static string ExpectedContentsTitle {
            get {
                return ResourceManager.GetString("ExpectedContentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; does not exist.
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name has been entered.
        /// </summary>
        internal static string FileNameHasBeenEntered {
            get {
                return ResourceManager.GetString("FileNameHasBeenEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form/Control/Id/Class.
        /// </summary>
        internal static string FormOrControlOrIdOrClassTitle {
            get {
                return ResourceManager.GetString("FormOrControlOrIdOrClassTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        internal static string FormTitle {
            get {
                return ResourceManager.GetString("FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Text.
        /// </summary>
        internal static string FreeTextTitle {
            get {
                return ResourceManager.GetString("FreeTextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id or .Class.
        /// </summary>
        internal static string IdOrClassTitle {
            get {
                return ResourceManager.GetString("IdOrClassTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input element was not found or more than one was found.
        /// </summary>
        internal static string InputElementNotFoundOrNotUnique {
            get {
                return ResourceManager.GetString("InputElementNotFoundOrNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input text.
        /// </summary>
        internal static string InputTitle {
            get {
                return ResourceManager.GetString("InputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance {0} of {1} not found.
        /// </summary>
        internal static string InstanceXOfYNotFound {
            get {
                return ResourceManager.GetString("InstanceXOfYNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markup validation failed.
        /// </summary>
        internal static string MarkupValidationFailed {
            get {
                return ResourceManager.GetString("MarkupValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No form context identified in preceding step/-s.
        /// </summary>
        internal static string NoFormContext {
            get {
                return ResourceManager.GetString("NoFormContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No id or class context identified in preceding step/-s.
        /// </summary>
        internal static string NoIdOrClassContext {
            get {
                return ResourceManager.GetString("NoIdOrClassContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexp. contents.
        /// </summary>
        internal static string NotExpectedContentsTitle {
            get {
                return ResourceManager.GetString("NotExpectedContentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open button was not pressed.
        /// </summary>
        internal static string OpenButtonWasNotPressed {
            get {
                return ResourceManager.GetString("OpenButtonWasNotPressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not select option for &apos;{0}&apos;.
        /// </summary>
        internal static string OptionToSelectNotFound {
            get {
                return ResourceManager.GetString("OptionToSelectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markup validation is denied for {0}.
        /// </summary>
        internal static string OucidResponseShouldNotSayMarkupValidation {
            get {
                return ResourceManager.GetString("OucidResponseShouldNotSayMarkupValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OustUnitTest.
        /// </summary>
        internal static string OustUnitTestWindowName {
            get {
                return ResourceManager.GetString("OustUnitTestWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oust.
        /// </summary>
        internal static string OustWindowName {
            get {
                return ResourceManager.GetString("OustWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing sub script {0}-{1}/{2}.
        /// </summary>
        internal static string ProcessingSubScripts {
            get {
                return ResourceManager.GetString("ProcessingSubScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving sub scripts.
        /// </summary>
        internal static string RetrievingSubScripts {
            get {
                return ResourceManager.GetString("RetrievingSubScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script call failed.
        /// </summary>
        internal static string ScriptCallFailed {
            get {
                return ResourceManager.GetString("ScriptCallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script executed without errors.
        /// </summary>
        internal static string ScriptExecutedWithoutErrors {
            get {
                return ResourceManager.GetString("ScriptExecutedWithoutErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script is obsolete or a sub script.
        /// </summary>
        internal static string ScriptIsObsoleteOrSubScript {
            get {
                return ResourceManager.GetString("ScriptIsObsoleteOrSubScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button in instance {0} of {1} not found or not unique.
        /// </summary>
        internal static string SubmitOrAnchorControlNotFoundOrNotUnique {
            get {
                return ResourceManager.GetString("SubmitOrAnchorControlNotFoundOrNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub script &quot;{0}&quot; could be used in script &quot;{1}&quot;.
        /// </summary>
        internal static string SubScriptCouldBeUsedInScript {
            get {
                return ResourceManager.GetString("SubScriptCouldBeUsedInScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub script &quot;{0}&quot; not found.
        /// </summary>
        internal static string SubScriptNotFound {
            get {
                return ResourceManager.GetString("SubScriptNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is Windows 11, so we need the displayed upload file input, but it was not found.
        /// </summary>
        internal static string ThisIsWindows11NeedUploadFileDisplayedInputButNotFound {
            get {
                return ResourceManager.GetString("ThisIsWindows11NeedUploadFileDisplayedInputButNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance {0} of {1} contains the unexpected contents &apos;{2}&apos;.
        /// </summary>
        internal static string UnexpectedContentsFound {
            get {
                return ResourceManager.GetString("UnexpectedContentsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected instance {0} of {1} was found.
        /// </summary>
        internal static string UnexpectedInstanceXOfYFound {
            get {
                return ResourceManager.GetString("UnexpectedInstanceXOfYFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string UrlTitle {
            get {
                return ResourceManager.GetString("UrlTitle", resourceCulture);
            }
        }
    }
}
