//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspenlaub.Net.GitHub.CSharp.Oust.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspenlaub.Net.GitHub.CSharp.Oust.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to called from.
        /// </summary>
        internal static string CalledFrom {
            get {
                return ResourceManager.GetString("CalledFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not clear window ID cookie.
        /// </summary>
        internal static string CouldNotClearWindowIdCookie {
            get {
                return ResourceManager.GetString("CouldNotClearWindowIdCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was logged, Oust will be closed.
        /// </summary>
        internal static string ExceptionWasLogged {
            get {
                return ResourceManager.GetString("ExceptionWasLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicating &apos;busy&apos;.
        /// </summary>
        internal static string IndicatingBusy {
            get {
                return ResourceManager.GetString("IndicatingBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicating &apos;idle&apos;.
        /// </summary>
        internal static string IndicatingIdle {
            get {
                return ResourceManager.GetString("IndicatingIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localhost is not available.
        /// </summary>
        internal static string LocalHostNotAvailable {
            get {
                return ResourceManager.GetString("LocalHostNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No script steps have been selected.
        /// </summary>
        internal static string NoScriptStepsHaveBeenSelected {
            get {
                return ResourceManager.GetString("NoScriptStepsHaveBeenSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only consecutive steps may be selected.
        /// </summary>
        internal static string OnlyConsecutiveStepsMayBeSelected {
            get {
                return ResourceManager.GetString("OnlyConsecutiveStepsMayBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OustUnitTest.
        /// </summary>
        internal static string OustUnitTestWindowName {
            get {
                return ResourceManager.GetString("OustUnitTestWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oust - Unit Test.
        /// </summary>
        internal static string OustUnitTestWindowTitle {
            get {
                return ResourceManager.GetString("OustUnitTestWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oust.
        /// </summary>
        internal static string OustWindowName {
            get {
                return ResourceManager.GetString("OustWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oust.
        /// </summary>
        internal static string OustWindowTitle {
            get {
                return ResourceManager.GetString("OustWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL server is not available.
        /// </summary>
        internal static string SqlServerNotAvailable {
            get {
                return ResourceManager.GetString("SqlServerNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub script name cannot be used (too short, invalid characters or already existing).
        /// </summary>
        internal static string SubScriptNameCannotBeUsed {
            get {
                return ResourceManager.GetString("SubScriptNameCannotBeUsed", resourceCulture);
            }
        }
    }
}
